- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
    args: [--markdown-linebreak-ext=md]
  - id: check-yaml
    args: ["-m", "--unsafe"]
    stages: [commit]
  - id: mixed-line-ending
    args: ["-f", "auto"]
    stages: [commit]
  - id: check-case-conflict
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: forbid-new-submodules
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
  - id: check-symlinks
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.2
  hooks:
  - id: shellcheck
    stages: [commit]
    args: ["-e", "SC1091"]
