{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hello-world-chart.serviceAccountName" . }}
  labels:
{{ include "hello-world-chart.labels" . | indent 4 }}
{{- end -}}
